version: "3.9"
services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend